// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9ZPyFgIsowUPxBek8d66IIKiAMJppi0',
    appId: '1:271334159747:web:cc1cc13ffb7eff2494f2b6',
    messagingSenderId: '271334159747',
    projectId: 'social-media-app-3d58e',
    authDomain: 'social-media-app-3d58e.firebaseapp.com',
    storageBucket: 'social-media-app-3d58e.appspot.com',
    measurementId: 'G-3R8DZ9G3YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2Nh6dqsY9qt928GOFHZI8MVaPXxxKxc',
    appId: '1:271334159747:android:fe9278960ef51e0b94f2b6',
    messagingSenderId: '271334159747',
    projectId: 'social-media-app-3d58e',
    storageBucket: 'social-media-app-3d58e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRa-4R4YcDQwi9OeyL8kqzqr8bO4x5p8w',
    appId: '1:271334159747:ios:f8a44ac2172f057694f2b6',
    messagingSenderId: '271334159747',
    projectId: 'social-media-app-3d58e',
    storageBucket: 'social-media-app-3d58e.appspot.com',
    iosBundleId: 'com.example.actonica',
  );
}
